### PR TITLE
Fix DNS record alignment issue

### LINKED ISSUE #673: Set standard width for DNS Record name
If the DNS Record name is longer or shorter, it pushes the alignment of the buttons beside it out of position.  We should fix this so the column is the same for all rows:

Screenshot 2023-04-26 at 7 53 49 PM

### PR DESCRIPTION
**Pull request by SerpentBytes**
## Description
Closes #673

### Demo

https://user-images.githubusercontent.com/50856799/234981029-65283f23-3b93-4864-b151-4592a37e6de7.mov

### CODE REVIEW

**Review by humphd — DISMISSED** [review]
This works great.  I wonder if we should switch to this sooner (e.g., on tablet sizes), since the table becomes hard to use unless fully expanded:

Screenshot 2023-04-27 at 5 08 39 PM

File: app/components/dns-record-table-row.tsx [hunk 1]
```diff
@@ -76,30 +76,56 @@ export default function DnsRecordsTableRow({
               {dnsRecord.expiresAt.toLocaleDateString('en-US')}
             </Text>
           </Show>
-          <ButtonGroup spacing={{ base: 'auto', sm: '0.5' }} width="full">
```
Comment (Eakam1007) [inline app/components/dns-record-table-row.tsx:79]: Is the only difference between the blocks inside the Hide and Show the styles on the ButtonGroup. That is, one has `spacing={{ base: 'auto', sm: '0.5' }} width="full"`, and the other doesn't ?

Comment (SerpentBytes) [reply app/components/dns-record-table-row.tsx:79]: Yes.

Comment (Eakam1007) [reply app/components/dns-record-table-row.tsx:79]: Instead of using Hide and Show for this, you can do this: 
image
Seems to work the same from my testing

**Review by Eakam1007 — CHANGES_REQUESTED** [review]

File: app/components/dns-record-table-row.tsx (hunk 1 above)
Comment (Eakam1007) [reply app/components/dns-record-table-row.tsx:79]: I didn't realize that the width would be the one causing the issue

**Review by Eakam1007 — APPROVED** [review]

**Comment by Eakam1007** [comment]
Thank you for investigating this. 
As for the tablet size, I think we need to come up with a new layout entirely. I am planning to work on it as part of #203 sometime next week

**Review by humphd — APPROVED** [review]
Awesome small fix!
